# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# defaults:
#   run:
#     shell: bash
#     # Define the working directory for all run steps in the workflow
#     working-directory: ./ansible-project/nodejs

jobs:
  build:

    runs-on: ubuntu-latest
    # env:
    #   working-directory: ./ansible-project/nodejs

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./ansible-project/nodejs/package-lock.json
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      # working-directory: ${{ env.working-directory}}
